//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SandRibbon.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://metl.adm.monash.edu.au/MeTL/docs/license.html")]
        public string LicenceUrl {
            get {
                return ((string)(this["LicenceUrl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://monash.edu/legals/privacy.html")]
        public string PrivacyUrl {
            get {
                return ((string)(this["PrivacyUrl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://monash.edu/legals/")]
        public string LegalsUrl {
            get {
                return ((string)(this["LegalsUrl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://monash.edu/")]
        public string CompanyUrl {
            get {
                return ((string)(this["CompanyUrl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.monash.edu/eeducation")]
        public string ContactUrl {
            get {
                return ((string)(this["ContactUrl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.monash.edu/eeducation/metl/what-is-metl.html")]
        public string DescriptionUrl {
            get {
                return ((string)(this["DescriptionUrl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.policy.monash.edu/policy-bank/management/its/acceptable-use-of-informa" +
            "tion-technology-facilities-by-students-policy.html")]
        public string StudentUsagePolicyUrl {
            get {
                return ((string)(this["StudentUsagePolicyUrl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.policy.monash.edu/policy-bank/management/its/it-use-policy-staff-and-a" +
            "uthorised.html")]
        public string StaffUsagePolicyUrl {
            get {
                return ((string)(this["StaffUsagePolicyUrl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://metl.adm.monash.edu.au/MeTL/MeTLPresenterReleaseNotes.txt")]
        public string ReleaseNotesUrl {
            get {
                return ((string)(this["ReleaseNotesUrl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://metl.adm.monash.edu.au/MeTL/docs/tabletSupport/MLS_UserAgreement.html")]
        public string UserAgreementUrl {
            get {
                return ((string)(this["UserAgreementUrl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://metl.adm.monash.edu.au/MeTL/docs/report_a_bug.html")]
        public string BugReportUrl {
            get {
                return ((string)(this["BugReportUrl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://metl.adm.monash.edu.au/MeTL/docs/tabletSupport/MLS_Tutorials.html")]
        public string TutorialUrl {
            get {
                return ((string)(this["TutorialUrl"]));
            }
        }
    }
}
